In [3]:
 
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv(r"F:/youtube-content-intelligence/data/raw/videos.csv")

df.head()

,channel,video_id,title,url,views,upload_date,duration_seconds,description,thumbnail,like_count,comment_count,channel_subscribers,tags
0,Matt Wolfe - Videos,XbHeJL45USQ,GLM-5.2 Proves Open-Source AI is Finally Good ...,https://www.youtube.com/watch?v=XbHeJL45USQ,23972,20260701,1732,"Z.ai's GLM-5.2 is a 1 million token, MIT-licen...",https://i.ytimg.com/vi/XbHeJL45USQ/maxresdefau...,1092.0,164.0,973000.0,"AI, Artificial Intelligence, FutureTools, Futu..."
1,Matt Wolfe - Videos,zMVZvgCOr40,AI News: The New Model That's As Good As Fable,https://www.youtube.com/watch?v=zMVZvgCOr40,97768,20260626,1200,Stop losing money on separate AI subscriptions...,https://i.ytimg.com/vi/zMVZvgCOr40/maxresdefau...,2979.0,210.0,973000.0,"AI, Artificial Intelligence, FutureTools, Futu..."
2,Matt Wolfe - Videos,STH929HARLo,9 Free AI Skills That Feel Like Cheat Codes,https://www.youtube.com/watch?v=STH929HARLo,78613,20260624,1754,9 free skills and plug-ins that make Claude Co...,https://i.ytimg.com/vi/STH929HARLo/maxresdefau...,3382.0,138.0,973000.0,"AI, Artificial Intelligence, FutureTools, Futu..."
3,Matt Wolfe - Videos,Db260rUuKJg,AI News: No One Saw This Coming!,https://www.youtube.com/watch?v=Db260rUuKJg,84265,20260619,2144,Here's The AI News You Probably Missed This We...,https://i.ytimg.com/vi/Db260rUuKJg/maxresdefau...,2879.0,353.0,973000.0,"AI, Artificial Intelligence, FutureTools, Futu..."
4,Matt Wolfe - Videos,_7BHqZayPOc,I Tried PewDiePie’s Odysseus AI So You Don’t H...,https://www.youtube.com/watch?v=_7BHqZayPOc,63604,20260617,1907,Try Recraft V4.1 now and experience an image g...,https://i.ytimg.com/vi/_7BHqZayPOc/maxresdefau...,1599.0,197.0,973000.0,"AI, Artificial Intelligence, FutureTools, Matt..."

In [5]:
print("Shape:", df.shape)

df.info()

Shape: (335, 13)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 335 entries, 0 to 334
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   channel              335 non-null    object
 1   video_id             335 non-null    object
 2   title                335 non-null    object
 3   url                  335 non-null    object
 4   views                335 non-null    int64
 5   upload_date          335 non-null    int64
 6   duration_seconds     335 non-null    int64
 7   description          335 non-null    object
 8   thumbnail            335 non-null    object
 9   like_count           334 non-null    float64
 10  comment_count        313 non-null    float64
 11  channel_subscribers  323 non-null    float64
 12  tags                 180 non-null    object
dtypes: float64(3), int64(3), object(7)
memory usage: 34.1+ KB

In [6]:
df.isnull().sum()

channel                  0
video_id                 0
title                    0
url                      0
views                    0
upload_date              0
duration_seconds         0
description              0
thumbnail                0
like_count               1
comment_count           22
channel_subscribers     12
tags                   155
dtype: int64

some missing values found in dataset

# Fill missing values

In [7]:
df["like_count"] = df["like_count"].fillna(0)

fill the miss count value with 0

In [8]:
df["comment_count"] = df["comment_count"].fillna(0)

fill the missing comment count value with zero

In [9]:
median_subs = df["channel_subscribers"].median()

df["channel_subscribers"] = df["channel_subscribers"].fillna(median_subs)

fill missing values of channel_subsctibers with the median of the column

In [10]:
df["tags"] = df["tags"].fillna("")

fill tag missing values with "" because tag type is object if we fill with nan it will fail the col

In [11]:
df.isnull().sum()

channel                0
video_id               0
title                  0
url                    0
views                  0
upload_date            0
duration_seconds       0
description            0
thumbnail              0
like_count             0
comment_count          0
channel_subscribers    0
tags                   0
dtype: int64

In [12]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

duplicate video records were checked using the unique video_id.

In [13]:
df["upload_date"] = pd.to_datetime(
    df["upload_date"],
    format="%Y%m%d"
)

df["upload_date"].head()

0   2026-07-01
1   2026-06-26
2   2026-06-24
3   2026-06-19
4   2026-06-17
Name: upload_date, dtype: datetime64[ns]

Upload dates were converted into datetime format

In [14]:
df["year"] = df["upload_date"].dt.year

df["month"] = df["upload_date"].dt.month_name()

df["day"] = df["upload_date"].dt.day_name()

Additional temporal features (Year, Month, Day) were extracted to support publishing frequency analysis.

In [15]:
# Duration in minutes

df["duration_minutes"] = (
    df["duration_seconds"] / 60
).round(2)

Video duration was converted from seconds to minutes to improve readability and simplify comparative analysis.

In [16]:
df["engagement_rate"] = (
    (df["like_count"] + df["comment_count"])
    / df["views"]
) * 100

df["engagement_rate"] = df["engagement_rate"].round(2)

(Likes + Comments)/ Views×100


Engagement Rate was calculated to evaluate audience interaction relative to total views

In [17]:
df["description_length"] = (
    df["description"]
    .fillna("")
    .str.len()
)

Description length was calculated to investigate whether detailed video descriptions are associated with higher audience engagement.

In [18]:
df["title_length"] = (
    df["title"]
    .str.len()
)

Title length was calculated to analyze whether concise or descriptive titles influence video popularity.

In [19]:
df["tag_count"] = (
    df["tags"]
    .fillna("")
    .apply(lambda x: len(x.split(",")) if x else 0)
)

Tag count was calculated to examine the relationship between metadata optimization and video performance.

In [20]:
df.info()

df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 335 entries, 0 to 334
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   channel              335 non-null    object
 1   video_id             335 non-null    object
 2   title                335 non-null    object
 3   url                  335 non-null    object
 4   views                335 non-null    int64
 5   upload_date          335 non-null    datetime64[ns]
 6   duration_seconds     335 non-null    int64
 7   description          335 non-null    object
 8   thumbnail            335 non-null    object
 9   like_count           335 non-null    float64
 10  comment_count        335 non-null    float64
 11  channel_subscribers  335 non-null    float64
 12  tags                 335 non-null    object
 13  year                 335 non-null    int32
 14  month                335 non-null    object
 15  day                  335 non-null    object
 16  duration_minutes     335 non-null    float64
 17  engagement_rate      335 non-null    float64
 18  description_length   335 non-null    int64
 19  title_length         335 non-null    int64
 20  tag_count            335 non-null    int64
dtypes: datetime64[ns](1), float64(5), int32(1), int64(5), object(9)
memory usage: 53.8+ KB

,channel,video_id,title,url,views,upload_date,duration_seconds,description,thumbnail,like_count,...,channel_subscribers,tags,year,month,day,duration_minutes,engagement_rate,description_length,title_length,tag_count
0,Matt Wolfe - Videos,XbHeJL45USQ,GLM-5.2 Proves Open-Source AI is Finally Good ...,https://www.youtube.com/watch?v=XbHeJL45USQ,23972,2026-07-01,1732,"Z.ai's GLM-5.2 is a 1 million token, MIT-licen...",https://i.ytimg.com/vi/XbHeJL45USQ/maxresdefau...,1092.0,...,973000.0,"AI, Artificial Intelligence, FutureTools, Futu...",2026,July,Wednesday,28.87,5.24,2023,50,27
1,Matt Wolfe - Videos,zMVZvgCOr40,AI News: The New Model That's As Good As Fable,https://www.youtube.com/watch?v=zMVZvgCOr40,97768,2026-06-26,1200,Stop losing money on separate AI subscriptions...,https://i.ytimg.com/vi/zMVZvgCOr40/maxresdefau...,2979.0,...,973000.0,"AI, Artificial Intelligence, FutureTools, Futu...",2026,June,Friday,20.00,3.26,2048,46,29
2,Matt Wolfe - Videos,STH929HARLo,9 Free AI Skills That Feel Like Cheat Codes,https://www.youtube.com/watch?v=STH929HARLo,78613,2026-06-24,1754,9 free skills and plug-ins that make Claude Co...,https://i.ytimg.com/vi/STH929HARLo/maxresdefau...,3382.0,...,973000.0,"AI, Artificial Intelligence, FutureTools, Futu...",2026,June,Wednesday,29.23,4.48,2653,43,27
3,Matt Wolfe - Videos,Db260rUuKJg,AI News: No One Saw This Coming!,https://www.youtube.com/watch?v=Db260rUuKJg,84265,2026-06-19,2144,Here's The AI News You Probably Missed This We...,https://i.ytimg.com/vi/Db260rUuKJg/maxresdefau...,2879.0,...,973000.0,"AI, Artificial Intelligence, FutureTools, Futu...",2026,June,Friday,35.73,3.84,2724,32,10
4,Matt Wolfe - Videos,_7BHqZayPOc,I Tried PewDiePie’s Odysseus AI So You Don’t H...,https://www.youtube.com/watch?v=_7BHqZayPOc,63604,2026-06-17,1907,Try Recraft V4.1 now and experience an image g...,https://i.ytimg.com/vi/_7BHqZayPOc/maxresdefau...,1599.0,...,973000.0,"AI, Artificial Intelligence, FutureTools, Matt...",2026,June,Wednesday,31.78,2.82,2290,63,28

In [21]:
df.isnull().sum()

channel                0
video_id               0
title                  0
url                    0
views                  0
upload_date            0
duration_seconds       0
description            0
thumbnail              0
like_count             0
comment_count          0
channel_subscribers    0
tags                   0
year                   0
month                  0
day                    0
duration_minutes       0
engagement_rate        0
description_length     0
title_length           0
tag_count              0
dtype: int64

In [22]:
df.describe()

,views,upload_date,duration_seconds,like_count,comment_count,channel_subscribers,year,duration_minutes,engagement_rate,description_length,title_length,tag_count
count,3.350000e+02,335,335.000000,335.000000,335.000000,3.350000e+02,335.000000,335.000000,335.000000,335.000000,335.000000,335.000000
mean,2.010042e+05,2026-01-21 17:11:38.507462656,1189.059701,7223.274627,490.131343,1.551532e+06,2025.641791,19.817552,3.827493,1613.002985,51.122388,8.450746
min,3.400000e+01,2011-05-23 00:00:00,94.000000,0.000000,0.000000,4.600000e+01,2011.000000,1.570000,0.000000,28.000000,15.000000,0.000000
25%,1.123550e+04,2026-03-10 12:00:00,600.000000,441.000000,49.500000,3.950000e+05,2026.000000,10.000000,3.225000,634.000000,38.000000,0.000000
50%,6.125900e+04,2026-05-15 00:00:00,1100.000000,2288.000000,226.000000,9.730000e+05,2026.000000,18.330000,3.740000,1362.000000,50.000000,2.000000
75%,1.617960e+05,2026-06-09 00:00:00,1597.500000,6458.500000,494.500000,1.820000e+06,2026.000000,26.625000,4.500000,2452.500000,61.500000,18.000000
max,3.227473e+06,2026-07-02 00:00:00,6447.000000,99685.000000,9500.000000,5.310000e+06,2026.000000,107.450000,8.330000,4845.000000,98.000000,47.000000
std,3.871659e+05,NaN,756.165450,13545.591427,865.432940,1.601662e+06,1.767144,12.602686,1.267190,1083.120203,17.533884,12.257582

In [24]:
df.to_csv(
    "F:/youtube-content-intelligence/data/raw/cleaned/videos_cleaned.csv",
    index=False
)

In [26]:
print("Data Cleaning Completed Successfully!")

Data Cleaning Completed Successfully!